spring:
  application:
    name: benz
  datasource:
    name: 测试库
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/accp_payment?serverTimezone=UTC&characterEncoding=utf-8
    username: accp_payment
    password: accp_payment
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      aop-patterns: com.benz.core.*
      async-close-connection-enable: true
  thymeleaf:
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
      #    servlet:
      #      content-type: text/html
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-handlers-package: com.benz.core.config
server:
  port: 8083
login:
  exclude:
    url:
      list: /druid/*,/login/doLogin,/login/verify,/register/apply,/register/verify,/register/operatorPasswordSet,/pages/404.html,/pages/error.html,/pages/login.html,/pages/register/apply.html,/pages/register/set-password.html,/receiveNotify,/pages/password-forget/apply.html,/pages/password-forget/confirm.html,/register/registerEmailSetApply,/user/findPwdApply,/user/findPwdVerify,/user/findPwdSmsApply,/user/findPwdSmsVerify,/pages/password-forget/result.html,pages/account/register/apply.html,/pages/account/register/set-password.html,/pages/auth/login.html,/pages/exception/404.html,
    redirect:
      list: /pages/register/apply.html,/pages/register/set-password.html,/pages/index.html,/pages/login.html
